
name: Auto Update & Deploy

on:
  push:
    branches:
      - release-json-1.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas

    - name: Convert CSV to JSON
      run: python scripts/update_json.py

    - name: Commit & Push JSON
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "chanont-h"
        git add functions_en_th_completed.json
        git commit -m "Auto Update JSON from CSV"
        git push
